### ISSUE TITLE
running and jumping

### ISSUE THREAD

**Issue by kilfoofan** [enBask/Enderkend#14]
When you run backwards from right to left, you press and hold the jump button. Mid flight you switch direction from left to right and keep holding jump button. On landing the character continues to run right to left.

**Comment by JamesRiav** [comment]
I experienced this too. Also, while holding [Right] and pressing [Left], you start moving left, which is great. When you let go of [Right], you stop moving entirely, even if you're still holding down [Left].

**Comment by Theformand** [comment]
I think its the same issue I'm seeing. 
Steps to repro:

Run right ( hold D)
Hit Jump
Run left (Hold A) while still running right (holding D)
At times it will stop you in your tracks. At other times it will keep running right. It doesnt always seem to use the latest input.

**Comment by whilke** [comment]
Fixed 
Commit: ac0786e41bb2f08271b1b4bc043791463318a3cf
