### ISSUE TITLE
Turrets - Strange Spawning Habbits

### ISSUE THREAD

**Issue by sdeming** [enBask/Enderkend#17]
Pair of turrets spawned together, one upright the other not. They were moving in unison up and down slowly while scanning and firing seemingly detached from any surface.

![image](https://cloud.githubusercontent.com/assets/33852/6546905/56958582-c59c-11e4-90b5-c276d29c9a41.png)

**Comment by whilke** [comment]
The collision pollys are big T's, so they are getting connected like a jigsaw. Turrets shouldn't be spawning that close to each other though!

**Comment by whilke** [comment]
fixed commit: 4f551efd14d0265c26544c841ba42e2cf594849f
