### ISSUE TITLE
Game opinions

### ISSUE THREAD

**Issue by Dreameh** [enBask/Enderkend#20]
# Opinions & Bugs
- Very darkish game (needs to be a bit brighter).
- Very hard game ( If you don't you cheatengine ;) ).
- Perhaps mobs are a bit OP (They pack a pretty good punch with those cannons).
- The font for the DASI interface is irritating (makes me not wanna read the stuffs).
- The mobs can be a bit too close if entering through a new door.
- Cannot for most part not see projectiles coming from mobs before it is too late. 
- The interface in general needs to feel like it is an terminal of sort, hence changing the color from white to maybe black and green :D ?

Will probs come more info later...

**Comment by whilke** [comment]
fixed lighting/door spawns: commit 7332b2a519d62d5edf967c02e14032681389f4c9
