### ISSUE TITLE
NPC's continue to aim akwardly

### ISSUE THREAD

**Issue by CranberryClock** [enBask/Enderkend#21]
BUILD: 3/7/2015
System: Win 64bit (7) and Win64bit (8.1) and Win 32bit(7)
Type: Graphical/Math

Occurs: when the NPC is in place it aims at the player non stop. This causes the NPC to always lock onto the player. While not an issue, the NPC will walk away from the player if not in focus causing the ARM to rotate backwards towards the player :: Gangsta:style.

See Image:
![goblin aim bug](https://cloud.githubusercontent.com/assets/987248/6565289/4babb8fa-c685-11e4-8f81-3f95c7a2fda9.PNG)

**Comment by whilke** [comment]
Fixed in commit: ac35ee78c561cd9c9279e7b48cebd45f953a1df8
