### ISSUE TITLE
Shooting Walls Horizontally = Bullets Going Vertically

### ISSUE THREAD

**Issue by sklasher** [enBask/Enderkend#27]
When you go near walls it will shoot your bullets vertically.. Also does the same at the main door at the beginning of the level... this also happens in the middle of the room when you put the mouse on the middle of the gun when the gun is horizontal...

http://imgur.com/jORwEcY (Against the Wall)
http://imgur.com/5dWe4AZ (Middle of the Room with mouse on top of gun)

**Comment by whilke** [comment]
Fixed commit: 3d0a6c72ad0b50b4dc13a41fb13f710a315655b7
