### ISSUE TITLE
Bring back the wider view

### ISSUE THREAD

**Issue by KatanoDK** [enBask/Enderkend#35]
I must say that I liked the wider view because it allowed you to be stealthier in the sense that you could sneak up on the opponents. The tuning could be more difficult if you could see your opponents before they shoot at you. Rogues are known as stealthy killers. Now granted that you shouldn't be able to zoom way out but a little wider view would be great.

**Comment by whilke** [comment]
We'll play with the viewspace, but the real issue is that no one should be shooting you off screen :).
