### ISSUE TITLE
even more door probzz

### ISSUE THREAD

**Issue by ghost** [enBask/Enderkend#9]
when i died while going into a door, it did't crash, all it did was make me able to control were the enemy were firing, but they were not, because i was dead

**Comment by ghost** [comment]
& my camera was slightly... okay exstreamly stuffed into the gound

**Comment by ghost** [comment]
btw this is how it looked http://imgur.com/GtbZRQB

**Comment by whilke** [comment]
fixed commit: 5e21608774b54bad4388008f087a83438840cda4
